# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from fundagent.v1 import ai_service_pb2 as fundagent_dot_v1_dot_ai__service__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fundagent/v1/ai_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_stream(
                '/fundagent.v1.AiService/Chat',
                request_serializer=fundagent_dot_v1_dot_ai__service__pb2.ChatRequest.SerializeToString,
                response_deserializer=fundagent_dot_v1_dot_ai__service__pb2.ChatEvent.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/fundagent.v1.AiService/Retrieve',
                request_serializer=fundagent_dot_v1_dot_ai__service__pb2.RetrieveRequest.SerializeToString,
                response_deserializer=fundagent_dot_v1_dot_ai__service__pb2.RetrieveResponse.FromString,
                _registered_method=True)
        self.IngestDocument = channel.unary_unary(
                '/fundagent.v1.AiService/IngestDocument',
                request_serializer=fundagent_dot_v1_dot_ai__service__pb2.IngestDocumentRequest.SerializeToString,
                response_deserializer=fundagent_dot_v1_dot_ai__service__pb2.IngestDocumentResponse.FromString,
                _registered_method=True)
        self.DeleteDocument = channel.unary_unary(
                '/fundagent.v1.AiService/DeleteDocument',
                request_serializer=fundagent_dot_v1_dot_ai__service__pb2.DeleteDocumentRequest.SerializeToString,
                response_deserializer=fundagent_dot_v1_dot_ai__service__pb2.DeleteDocumentResponse.FromString,
                _registered_method=True)


class AiServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Chat(self, request, context):
        """Agent 问答。客户端取消 / 超时 → 服务端的 Agent 生成器被取消，取消沿 LangGraph → LLM / MCP 调用传播。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=fundagent_dot_v1_dot_ai__service__pb2.ChatRequest.FromString,
                    response_serializer=fundagent_dot_v1_dot_ai__service__pb2.ChatEvent.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=fundagent_dot_v1_dot_ai__service__pb2.RetrieveRequest.FromString,
                    response_serializer=fundagent_dot_v1_dot_ai__service__pb2.RetrieveResponse.SerializeToString,
            ),
            'IngestDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestDocument,
                    request_deserializer=fundagent_dot_v1_dot_ai__service__pb2.IngestDocumentRequest.FromString,
                    response_serializer=fundagent_dot_v1_dot_ai__service__pb2.IngestDocumentResponse.SerializeToString,
            ),
            'DeleteDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDocument,
                    request_deserializer=fundagent_dot_v1_dot_ai__service__pb2.DeleteDocumentRequest.FromString,
                    response_serializer=fundagent_dot_v1_dot_ai__service__pb2.DeleteDocumentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fundagent.v1.AiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fundagent.v1.AiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/fundagent.v1.AiService/Chat',
            fundagent_dot_v1_dot_ai__service__pb2.ChatRequest.SerializeToString,
            fundagent_dot_v1_dot_ai__service__pb2.ChatEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fundagent.v1.AiService/Retrieve',
            fundagent_dot_v1_dot_ai__service__pb2.RetrieveRequest.SerializeToString,
            fundagent_dot_v1_dot_ai__service__pb2.RetrieveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fundagent.v1.AiService/IngestDocument',
            fundagent_dot_v1_dot_ai__service__pb2.IngestDocumentRequest.SerializeToString,
            fundagent_dot_v1_dot_ai__service__pb2.IngestDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fundagent.v1.AiService/DeleteDocument',
            fundagent_dot_v1_dot_ai__service__pb2.DeleteDocumentRequest.SerializeToString,
            fundagent_dot_v1_dot_ai__service__pb2.DeleteDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
